# ================== MongoDB Local Connection ==================
# Assuming default Campus MongoDB installation on localhost and default port 27017
spring.data.mongodb.uri=mongodb://localhost:27017/ticketdb
spring.data.mongodb.database=ticketdb
spring.data.mongodb.repositories.enabled=true
# JWT configuration
app.jwt.secret=fcd7845a-26a8-4bb7-8b5e-763d21541952
app.jwt.expiration=3600000   # 1 hour in milliseconds
